### ISSUE TITLE
Update UI to accommodate new features.

### ISSUE THREAD

**Issue by jkulka** [ambient-jrc/ambient-lightbulb#4]
Do work in branch called issue-04

**Comment by calmaruy** [comment]
[Yeelight_HTML.txt](https://github.com/ambient-jrc/ambient-lightbulb/files/3022056/Yeelight_HTML.txt)
Starting template, just need to fix the functions to the buttons. I think the first three should work, however the Honolulu-temp button does not yet because I don't exactly know how to call or rather which function to call
